exclude: "build|egg-info|dist"

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: end-of-file-fixer

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3.7
        args: ["--config", ".black.toml"]
  - repo: local
    hooks:
      - id: clang-format
        name: Run clang-format
        entry: clang-format -i
        types: [text]
        files: '.*\.cpp$|.*\.h$|.*\.cu$|.*\.hpp$'
        language: system
